### ISSUE TITLE
mysql error if you delete and restore, then delete

### ISSUE THREAD

**Issue by metulburr** [burnacid/MyBB-Trash-Bin#10]
My sequence of events were...
made single post thread, deleted, restored thread, posted second post, attempted to delete thread again and got mysql error

MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1062 - Duplicate entry '2880' for key 'PRIMARY'
Query:
INSERT INTO mybb_backup_threads (tid,fid,subject,prefix,icon,poll,uid,username,dateline,firstpost,lastpost,lastposter,lastposteruid,views,replies,closed,sticky,numratings,totalratings,notes,visible,unapprovedposts,deletedposts,attachmentcount,deletetime,tlink,postpreview,lastpostpreview) VALUES ('2880','27','testing trashbin','0','0','0','1','metulburr','1492426282','15148','1492426345','metulburr','1','5','1','','0','0','0','','1','0','0','1','0','','','testing 2nd post')

**Comment by burnacid** [comment]
did you have another SQL error before this one?
Because there was an issue which generates an SQL error. Then after you will run in this problem.

Version 1.1.2 was released this morning which removes the first problem. To fix this you need to remove the duplicate keys from the database.

**Comment by metulburr** [comment]
> did you have another SQL error before this one?
No this is the first MySQL error i got from this plugin

>  Version 1.1.2 was released this morning which removes the first problem
I actually freshly installed it this morning after i saw the update. Yesterday i saw the plugin but was on a tablet and didnt want to fuss with installing it with that. So i waited to get to a desktop and was reminded of this plugin after i saw the update.

**Comment by burnacid** [comment]
That is weird. Then you should not possibly get a duplicate. I'll see if i might do a check for duplicate.

**Comment by metulburr** [comment]
I found the problem. The undo delete plugin retained the thread as well. As soon as i truncated the thread from there i was able to delete the post again
https://mods.mybb.com/view/undo-delete
