### ISSUE TITLE
Incompatibility with PHP8

### ISSUE THREAD

**Issue by Tarekma7** [burnacid/MyBB-Trash-Bin#24]
After upgrade from PHP 7.4 to PHP 8 om mybb 1.8.30, the Trash bin plugin shows many errors and is not working properly 

Reverting back to PHP 7.4, everything returned working with no problems

Please update the plugin

**Comment by burnacid** [comment]
Need to find the time to do this. Can't at this moment promise this on short time

**Comment by Tarekma7** [comment]
Any hope to have an updated version of this very useful plugin?

**Comment by Tarekma7** [comment]
I tested the last version again with PHP8 and the file inc/plugin/trashbin.php causes adminCP/Plugin page to be broken and once this file is deleted, plugin page is working again

**Comment by burnacid** [comment]
Please check the development branch: https://github.com/burnacid/MyBB-Trash-Bin/tree/Development

**Comment by Tarekma7** [comment]
Working perfect for me, thanks so much
