### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Beremix** [burnacid/MyBB-Trash-Bin#8]
Warning [2] require_once(PLUGINLIBRARY): failed to open stream: No such file or directory - Line: 419 - File: inc/plugins/trashbin.php PHP 5.6.30 (Linux)
This warning I get when I'm at "Post Trash Bin"
File	Line	Function
/inc/plugins/trashbin.php	419	errorHandler->error
/inc/plugins/trashbin.php	419	trashbin::build_url
/admin/modules/tools/trashbin.php	117	trashbin->build_url
/admin/index.php	803	require

I have added pluginlibary to the forum, but I get this when trying to activate it:
The selected plugin does not have to be activated.

**Comment by burnacid** [comment]
Can you see the plugin library within your form plugins?

**Comment by burnacid** [comment]
@Beremix are you still having this issue?

**Comment by Beremix** [comment]
Hey.

Mybb version: 1.8.10
PluginLibrary (12)

And yeah I have pluginlibrary.php in my plugins folder.

**Comment by burnacid** [comment]
I can't reproduce it sadly

**Comment by burnacid** [comment]
@Beremix this could be fixed in v1.1.3
